# Generated by Django 3.2.2 on 2022-12-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_name_account_user_alter_account_nid_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/projcet_images/'),
        ),
    ]
